name: Davide Sauce Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
    paths:
      - 'apps/davide-sauce/**'
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build Production and Generate Sitemap
        run: |
          npx nx run davide-sauce:build:production
          node ./tools/sitemap.js --domain=https://davidesauce.com --routes=../apps/davide-sauce/src/app/app.routes.ts --out=./dist/apps/davide-sauce/browser
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAVIDE_SAUCE_FIREBASE }}'
          channelId: live
          projectId: davide-sauce-firebase
          target: davide-sauce
