name: Forest Bjorn Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
    paths:
      - 'apps/forest-bjorn/**'
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build Production and Generate Sitemap
        run: |
          npx nx run forest-bjorn:build:production
          node ./tools/sitemap.js --domain=https://forestbjorn.com --routes=../apps/forest-bjorn/src/app/app.routes.ts --out=./dist/apps/forest-bjorn/browser
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOREST_BJORN_PHOTOGRAPHY }}'
          channelId: live
          projectId: forest-bjorn-photography
          target: forest-bjorn
